### ISSUE TITLE
timestamp info message

### ISSUE THREAD

**Issue by Munskin** [baasdesign/Brodor#14]
Een gebruiker moet kunnen zien van wanneer een bepaald bericht is. MomentJS kan hiervoor gebruikt worden. Twee opties: relative, `moment().startOf('day').fromNow();        // 9 hours ago` of  locale,
`moment().format('LLL');  // 30 juni 2016 09:07`

**Comment by baasdesign** [comment]
Ja prima. Kunnen we dan niet de eerste gebruiken, en als die meer dan 24 uur geleden is de tweede gebruiken?

**Comment by baasdesign** [comment]
beetje ala whatsapp
